INSERT INTO contact ( ID, NAME, CELLPHONE, OBJECT_ID, OBJECT_TYPE, CREATED_AT, CREATED_BY, MAIN, FLAG_ACTIVE) VALUES (1,'Joao', '034999909311', 1, 1, TO_DATE('05/09/2018','dd/MM/RRRR'), 'SYSTEM', true, true);
INSERT INTO contact ( ID, NAME, CELLPHONE, OBJECT_ID, OBJECT_TYPE, CREATED_AT, CREATED_BY, FLAG_ACTIVE) VALUES (2,'Maria', '034999909311', 1, 1, TO_DATE('05/09/2018','dd/MM/RRRR'), 'SYSTEM', true);
INSERT INTO contact ( ID, NAME, CELLPHONE, OBJECT_ID, OBJECT_TYPE, CREATED_AT, CREATED_BY, MAIN, FLAG_ACTIVE) VALUES (3,'Caetano', '034999909010', 2, 1, TO_DATE('05/09/2018','dd/MM/RRRR'), 'SYSTEM', true, true);

INSERT INTO PATIENT ( ID, NAME, DOCUMENT_NUMBER, CREATED_AT, CREATED_BY, BIRTHDATE, NACIONALITY, SEX, CIVIL_STATUS, JOB)
VALUES ( 1,'JOAO LUDOVICO', '09574539652', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM', TO_DATE('25/01/1991','DD/MM/RRRR'), 'BRASILEIRA', 'M', 'SOLTEIRO', 'ANALISTA DE TI' );

INSERT INTO EXAM_REQUEST ( ID, MEDICAL_RECORD, MEDICAL_REQUEST, SECTOR, DOCTOR_REQUESTANT, USER_REQUEST, PATIENT_ID, REQUEST_DATE, CREATED_AT, CREATED_BY )
values (1, 333, 333, 'UFU', 'PAULO', 'TESTE', 1, TO_DATE('05/09/2018','DD/MM/RRRR'), TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');

INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (1, 'mg', 'miligramas');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (2, 'g', 'gramas');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (3, 'ml', 'mililitros');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (4, 'l', 'litros');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (5, 'cmp', 'comprimido');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (6, 'unit', 'unidade');

INSERT INTO MEDICAMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (1, 'DIPIRONA', 'teste', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');
INSERT INTO MEDICAMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (2, 'ANTI-INFLAMATORIO', 'teste', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');

INSERT INTO EXAM ( ID, CLINICAL_DATA, PATIENT_ID, ACHIEVEMENT_DATE, CREATED_AT, CREATED_BY )
values (1, 'TESTE', 1, TO_DATE('10/10/2018','DD/MM/RRRR'), TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');

INSERT INTO EXAM_MEDICAMENT ( ID, EXAM_ID, MEDICAMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (1, 1, 2, 1, 50, TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');
INSERT INTO EXAM_MEDICAMENT ( ID, EXAM_ID, MEDICAMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (2, 1, 1, 2, 1, TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');

INSERT INTO EQUIPMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (1, 'BRAINVISIAN', 'teste', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');
INSERT INTO EQUIPMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (2, 'ELETRODOS', 'teste', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');

INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (1, 1, 2, 6, 20, TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');
INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (2, 1, 1, 6, 1, TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');

INSERT INTO EPOCH ( ID, EXAM_ID, START_TIME, DURATION, DESCRIPTION, CREATED_AT, CREATED_BY )
values (1, 1, 320, 120, 'Em Silêncio', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');
INSERT INTO EPOCH ( ID, EXAM_ID, START_TIME, DURATION, DESCRIPTION, CREATED_AT, CREATED_BY )
values (2, 1, 120, 120, 'Musica Boa', TO_DATE('05/09/2018','DD/MM/RRRR'), 'SYSTEM');