INSERT INTO contact ( ID, NAME, CELLPHONE, OBJECT_ID, OBJECT_TYPE, CREATED_AT, CREATED_BY, MAIN, FLAG_ACTIVE) VALUES (1,'Joao', '034999909311', 1, 1, DATE '2018-09-05', 'SYSTEM', true, true);
INSERT INTO contact ( ID, NAME, CELLPHONE, OBJECT_ID, OBJECT_TYPE, CREATED_AT, CREATED_BY, FLAG_ACTIVE) VALUES (2,'Maria', '034999909311', 1, 1, DATE '2018-09-05', 'SYSTEM', true);
INSERT INTO contact ( ID, NAME, CELLPHONE, OBJECT_ID, OBJECT_TYPE, CREATED_AT, CREATED_BY, MAIN, FLAG_ACTIVE) VALUES (3,'Caetano', '034999909010', 2, 1, DATE '2018-09-05', 'SYSTEM', true, true);

INSERT INTO PATIENT ( ID, NAME, DOCUMENT_NUMBER, CREATED_AT, CREATED_BY, BIRTHDATE, NATIONALITY, SEX, CIVIL_STATUS, JOB)
VALUES ( NEXT VALUE FOR PATIENT_SQ,'JOAO LUDOVICO', '09574539652', DATE '2018-09-05', 'SYSTEM', DATE '1991-01-25', 'BRASILEIRA', 'MALE', 'SINGLE', 'ANALISTA DE TI' );

INSERT INTO EXAM_REQUEST ( ID, MEDICAL_RECORD, MEDICAL_REQUEST, SECTOR, DOCTOR_REQUESTANT, USER_REQUEST, PATIENT_ID, REQUEST_DATE, CREATED_AT, CREATED_BY )
values ( NEXT VALUE FOR EXAM_REQUEST_SQ, 333, 333, 'UFU', 'PAULO', 'TESTE', 1, DATE '2018-09-05', DATE '2018-09-05', 'SYSTEM');

INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (1, 'mg', 'miligramas');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (2, 'g', 'gramas');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (3, 'ml', 'mililitros');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (4, 'l', 'litros');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (5, 'cmp', 'comprimido');
INSERT INTO UNIT (ID, NAME, DESCRIPTION) VALUES (6, 'unit', 'unidade');

INSERT INTO MEDICAMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (NEXT VALUE FOR MEDICAMENT_SQ, 'DIPIRONA', 'teste', DATE '2018-09-05', 'SYSTEM');
INSERT INTO MEDICAMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (NEXT VALUE FOR MEDICAMENT_SQ, 'ANTI-INFLAMATORIO', 'teste', DATE '2018-09-05', 'SYSTEM');

INSERT INTO EXAM ( ID, CLINICAL_DATA, PATIENT_ID, ACHIEVEMENT_DATE, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_SQ, 'TESTE', 1, DATE '2018-10-10', DATE '2018-09-05', 'SYSTEM');

INSERT INTO EXAM_MEDICAMENT ( ID, EXAM_ID, MEDICAMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_MEDICAMENT_SQ, 1, 2, 1, 50, DATE '2018-09-05', 'SYSTEM');
INSERT INTO EXAM_MEDICAMENT ( ID, EXAM_ID, MEDICAMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_MEDICAMENT_SQ, 1, 1, 2, 1, DATE '2018-09-05', 'SYSTEM');

INSERT INTO EQUIPMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (NEXT VALUE FOR EQUIPMENT_SQ, 'BRAINVISIAN', 'teste', DATE '2018-09-05', 'SYSTEM');
INSERT INTO EQUIPMENT (ID, NAME, DESCRIPTION, CREATED_AT, CREATED_BY) VALUES (NEXT VALUE FOR EQUIPMENT_SQ, 'ELETRODOS', 'teste', DATE '2018-09-05', 'SYSTEM');

INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_EQUIPMENT_SQ, 1, 2, 6, 20, DATE '2018-09-05', 'SYSTEM');
INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_EQUIPMENT_SQ, 1, 1, 6, 1, DATE '2018-09-05', 'SYSTEM');

INSERT INTO EPOCH ( ID, EXAM_ID, START_TIME, DURATION, DESCRIPTION, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EPOCH_SQ, 1, 320, 120, 'Em Silêncio', DATE '2018-09-05', 'SYSTEM');
INSERT INTO EPOCH ( ID, EXAM_ID, START_TIME, DURATION, DESCRIPTION, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EPOCH_SQ, 1, 120, 120, 'Musica Boa', DATE '2018-09-05', 'SYSTEM');


INSERT INTO PATIENT ( ID, NAME, DOCUMENT_NUMBER, CREATED_AT, CREATED_BY, BIRTHDATE, NATIONALITY, SEX, JOB)
VALUES ( NEXT VALUE FOR PATIENT_SQ,'V019', '00000000019', DATE '2017-06-30', 'SYSTEM', DATE '1991-01-01', 'BRASILEIRA', 'MALE', 'ESTUDANTE' );
INSERT INTO EXAM ( ID, CLINICAL_DATA, PATIENT_ID, ACHIEVEMENT_DATE, CREATED_AT, CREATED_BY, HEIGHT, WEIGHT )
values ( NEXT VALUE FOR EXAM_SQ, NULL, 2, DATE '2016-12-20', DATE '2017-06-30', 'SYSTEM', 175, 71);
INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_EQUIPMENT_SQ, 2, 2, 6, 20, DATE '2017-06-30', 'SYSTEM');
INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_EQUIPMENT_SQ, 2, 1, 6, 1, DATE '2017-06-30', 'SYSTEM');
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 1', 2, 2, 219, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 2', 2, 2, 224, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 3', 2, 2, 255, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 4', 2, 2, 263, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 5', 2, 2, 276, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 6', 2, 2, 283, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 7', 2, 2, 289, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 8', 2, 2, 310, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 9', 2, 2, 316, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 10', 2, 2, 321, NEXT VALUE FOR EPOCH_SQ);

INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Vazio (Gravado com eletrodos soltos)', 180, 2, 0, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos Fechados', 180, 2, 180, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos Abertos', 180, 2, 360, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Hiperventilação', 120, 2, 540, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Descanso Hiperventilação', 120, 2, 660, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Cálculos Matemáticos', 29, 2, 780, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Leitura / Resposta de palavras', 131, 2, 810, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Mordedura', 30, 2, 942, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Franzir Testa', 27, 2, 972, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Piscar', 15, 2, 1000, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Movimentos Oculares', 14, 2, 1015, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Musica', 60, 2, 1029, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos Fechados Música', 60, 2, 1089, NEXT VALUE FOR ACTIVITY_SQ);


INSERT INTO PATIENT ( ID, NAME, DOCUMENT_NUMBER, CREATED_AT, CREATED_BY, BIRTHDATE, NATIONALITY, SEX, JOB)
VALUES ( NEXT VALUE FOR PATIENT_SQ,'V021', '00000000021', DATE '2017-06-30', 'SYSTEM', DATE '1974-01-01', 'BRASILEIRA', 'FEMALE', 'COORDENADORA DE ESCRITÓRIO' );
INSERT INTO EXAM ( ID, CLINICAL_DATA, PATIENT_ID, ACHIEVEMENT_DATE, CREATED_AT, CREATED_BY, HEIGHT, WEIGHT )
values ( NEXT VALUE FOR EXAM_SQ, NULL, 3, DATE '2016-12-20', DATE '2017-06-30', 'SYSTEM', 160, 54);
INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_EQUIPMENT_SQ, 3, 2, 6, 20, DATE '2017-06-30', 'SYSTEM');
INSERT INTO EXAM_EQUIPMENT ( ID, EXAM_ID, EQUIPMENT_ID, UNIT_ID, AMOUNT, CREATED_AT, CREATED_BY )
values (NEXT VALUE FOR EXAM_EQUIPMENT_SQ, 3, 1, 6, 1, DATE '2017-06-30', 'SYSTEM');
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 1', 2, 3, 206, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 2', 2, 3, 210, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 3', 2, 3, 225, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 4', 2, 3, 267, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 5', 2, 3, 275, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 6', 2, 3, 285, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 7', 2, 3, 287, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 8', 2, 3, 293, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 9', 2, 3, 314, NEXT VALUE FOR EPOCH_SQ);
INSERT INTO EPOCH (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos fechados 10', 2, 3, 328, NEXT VALUE FOR EPOCH_SQ);

INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Vazio (Gravado com eletrodos soltos)', 180, 3, 0, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos Fechados', 180, 3, 223, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Olhos Abertos', 180, 3, 403, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Hiperventilação', 120, 3, 583, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Descanso Hiperventilação', 120, 3, 703, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Cálculos Matemáticos', 46, 3, 823, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Leitura / Resposta de palavras', 127, 3, 869, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Mordedura', 31, 3, 996, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Franzir Testa', 28, 3, 1027, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Piscar', 13, 3, 1055, NEXT VALUE FOR ACTIVITY_SQ);
INSERT INTO ACTIVITY (CREATED_AT, CREATED_BY, DESCRIPTION, DURATION, EXAM_ID, START_TIME, ID)
VALUES (DATE '2017-06-30', 'SYSTEM', 'Movimentos Oculares', 11, 3, 1068, NEXT VALUE FOR ACTIVITY_SQ);

